# Generated by Django 2.1.5 on 2021-08-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='slug',
        ),
        migrations.AddField(
            model_name='userlike',
            name='category',
            field=models.ManyToManyField(to='rango.Category'),
        ),
    ]
