# Generated by Django 2.1.5 on 2021-08-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210803_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userview',
            name='number',
        ),
    ]
