# Generated by Django 2.1.5 on 2021-08-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_remove_userview_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userview',
            name='page',
        ),
        migrations.AddField(
            model_name='userview',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rango.Page'),
        ),
    ]
