# Generated by Django 2.1.5 on 2021-08-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210803_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userview',
            name='check',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
