# Generated by Django 2.1.5 on 2021-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userview_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='category',
            field=models.ManyToManyField(to='rango.Category'),
        ),
        migrations.AddField(
            model_name='userlike',
            name='check',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
