# Generated by Django 2.1.5 on 2021-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210803_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_category',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='slug',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='title',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userviews',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
