# Generated by Django 2.1.5 on 2021-08-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210803_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='category',
        ),
        migrations.AddField(
            model_name='userlike',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
        ),
    ]
