# Generated by Django 2.1.5 on 2021-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210803_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
