# Generated by Django 2.1.5 on 2021-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210803_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='liked_title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
